openapi: 3.0.1
info:
  title: Knight Moves API
  description: "This is the API docs for Knight Moves project"
  version: 1.0.0
servers:
  - url: https://localhost:3000/api

tags:
  - name: Knight Moves
paths:
  /knightmoves/:position:
    get:
      tags:
        - Knight Moves
      summary: Retrieve and object with the first and second turn positions of the knight piece
      parameters:
        - in: path
          name: position
          required: true
          schema:
            type: string
          example: A8
          description: "This is the position corresponding to a square in the chessboard Examples: A8, D5, H1,..."
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MovesReturn"

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input position

        500:
          description: Internal Server Error

components:
  schemas:
    MovesReturn:
      type: object
      properties:
        position:
          type: string
          example: A8
        firstTurn:
          type: array
          items:
            type: string
            example:
              - B6
              - C7
        secondTurn:
          type: array
          items:
            type: string
            example:
              - C4
              - A4
              - C8
              - A8
              - D5
              - D7
              - B5
              - E6
              - A6
              - E8
